version: '3'
services:
  postgres:
    container_name: gestao-contas-domesticas-postgres
    image: postgres:13
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 123456
      POSTGRES_DB: gestao-contas-domesticas
#      deveria ser utilizado portas porém devido ao tempo optei por utilizar mode host
    network_mode: host
    restart: always
  gestao-contas-domesticas-api:
    build: ./backend
#      deveria ser utilizado portas porém devido ao tempo optei por utilizar mode host
    network_mode: host
    depends_on:
      - postgres
  gestao-contas-domesticas-frontend:
    build: ./frontend
#      deveria ser utilizado portas porém devido ao tempo optei por utilizar mode host
    network_mode: host
    depends_on:
      - gestao-contas-domesticas-api
